### ISSUE TITLE
`npm run dev`  references in readme does not work

### ISSUE THREAD

**Issue by gwpl** [craigsdennis/talk-to-javascript-openai-workers#2]
https://github.com/craigsdennis/talk-to-javascript-openai-workers/blob/60fe0118c11aca4c1d56f72de41b522825f5a62e/README.md?plain=1#L21

```
$ npm install
(...)
$ npm start dev
 
> talk-to-javascript@0.0.0 start
> wrangler dev dev


 ⛅ wrangler 3.95.0 (update available 3.99.0)
-------------------------------------------------------


✘ [ERROR] The entry-point file at "dev" was not found.


🪵  Logs were written to "/home/user/.config/.wrangler/logs/wrangler-2024-12-22_18-00-47_146.log"
```

logs:
[log-talk-to-js.log](https://github.com/user-attachments/files/18222830/log-talk-to-js.log)

**Comment by craigsdennis** [comment]
Did you do this line? 

> Copy [.dev.vars.example](https://github.com/craigsdennis/talk-to-javascript-openai-workers/blob/main/.dev.vars.example) to .dev.vars and fill out your OpenAI API Key.

**Comment by craigsdennis** [comment]
It's `npm run dev`

**Comment by craigsdennis** [comment]
I'm going to close this issue due to typo, but let me know if you are still having issues. Thank you for reporting
